name: Build Android and iOS apps

on: push

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Retrieve/update cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install npm dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install
      - run: yarn test

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Retrieve/update cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install npm dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease -PgithubActionsRNpoc_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PgithubActionsRNpoc_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

  build-ios:
    needs: install-and-test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Retrieve/update cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install npm dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install

      - name: Install pod dependencies
        run: |
          cd ios && pod install

      - name: Build app
        run: yarn react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/ios-app.jsbundle --assets-dest ios

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ios-app.jsbundle
          path: ios/ios-app.jsbundle
